apiVersion: v1
kind: ConfigMap
metadata:
  name: config-mysql
  namespace: automarket
data:
  MYSQL_DATABASE: "automarket_db"
  MYSQL_USER: "automarket_user"
  MYSQL_HOST: "mysql-svc"
  MYSQL_PORT: "3306"
  
    