apiVersion: v1
kind: Secret
metadata:
  name: automarket-mysql-secret
  namespace: automarket
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: automarket_mysql
  MYSQL_DATABASE: automarket_db
  MYSQL_USER: automarket_user
  MYSQL_PASSWORD: automarket