apiVersion: v1
kind: ConfigMap
metadata:
  name: config-postgres
  namespace: automarket
data:
  POSTGRES_DB: "automarket_db"
  POSTGRES_USER: "automarket_user"
  POSTGRES_HOST: "postgres-svc"
  POSTGRES_PORT: "5432"
  
    