apiVersion: v1
kind: Secret
metadata:
  name: automarket-db-secret
  namespace: automarket
type: Opaque
stringData:
  POSTGRES_USER: automarket_user
  POSTGRES_PASSWORD: automarket
  POSTGRES_DB: automarket_db